# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29b97bdaecb06ebbad77d7b71475b4f2e2b5bee7f77ba38058b7b2612a783c96c2d25f61566d2e74991d8ca6b065b03215d21094c2eb6c1bf04df56187a28a5b

test:
  secret_key_base: 43ef43ad62cc3091ec546c0f6ae843d8534639e0db791fad813b8aa2182872944fee49e42a537071552fe96c9c7ad84237d36ef791e0ffae3abf9f36d4a11e53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
